version: "3.8"
services:
    http:
        image: registry.hub.docker.com/library/nginx:1.19-alpine
        ports:
            - "${PF_HTTP_PORT:-8080}:80"
        volumes:
            - ./docker/http/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public:/var/psr-portfolio/public:rw
    php:
        build:
            target: dev
            dockerfile: ./docker/php/Dockerfile
            context: .
        volumes:
            - ./:/var/psr-portfolio:rw
        tmpfs:
            - /var/psr-portfolio/var:mode=700,uid=82,gid=82
