version: "3.8"
services:
    http:
        image: ghcr.io/hermann8u/psr-portfolio/http:latest
        depends_on:
            - php
        ports:
            - "${PF_HTTP_PORT:-8080}:80"
    php:
        image: ghcr.io/hermann8u/psr-portfolio/php:latest
        tmpfs:
            - /var/psr-portfolio/var:mode=700,uid=82,gid=82
