version: "3.8"
services:
    http:
        image: psr-portfolio_http:latest
        ports:
            - "${PF_HTTP_PORT:-8080}:80"
    php:
        image: psr-portfolio_php:latest
        tmpfs:
            - /var/psr-portfolio/var:mode=700,uid=82,gid=82
