version: "3.8"
services:
    http:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "${PF_HTTP_PORT:-8080}:80"
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        tmpfs:
            - /var/psr-portfolio/var:mode=700,uid=82,gid=82
