# The application routes

home:
    path: '/'
    controller: 'App\Action\HomeAction'
    methods: ['GET']

projects:
    path: '/projects'
    controller: 'App\Action\ProjectsAction'
    methods: ['GET']
