# The application routes

home:
    path: '/'
    controller: App\Action\HomeAction
    methods: ['GET']

projects:
    path: '/projects'
    controller: App\Action\ProjectsAction
    methods: ['GET']

stats:
    path: '/_stats'
    controller: App\Action\GetStatsAction
    methods: ['GET']
