# This file is the entry point to configure the application's services.

# Files in the packages/ subdirectory configure your dependencies.
imports:
    - { resource: packages/* }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        public: false
        bind:
            string $projectDir: '%app.project_dir%'
            bool $debug: '%app.debug%'

    _instanceof:
        Twig\Extension\ExtensionInterface:
            tags: ['twig.extension']

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Kernel.php}'

    # The actions are registered separately because they need to be public and in order to add them the "app.action" tag
    App\Action\:
        resource: '../src/Action'
        public: true
        tags: ['app.action']

    # The request handler goal is to execute the middleware stack given as arguments
    # You should complete this list with your own middleware
    # !! Warning !! Order matters
    App\RequestHandler:
        public: true
        arguments:
            - '@App\Middleware\ExceptionHandler'
            - '@App\Middleware\Twig'
            - '@App\Middleware\Router'
            - '@App\Middleware\ActionHandler'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Middleware\Twig:
        arguments:
            - '@Twig\Environment'
            - !tagged 'twig.extension'
