name: Push Docker images to GitHub
on:
    push:
        branches:
            - master
jobs:
    push:
        runs-on: ubuntu-latest
        environment:
            name: prod
        steps:
            -   uses: actions/checkout@v2
            -   name: Build image
                run: |
                    docker build . --file ./docker/php/Dockerfile --tag ghcr.io/${{ github.repository }}/php:latest
                    docker build . --file ./docker/http/Dockerfile --tag ghcr.io/${{ github.repository }}/http:latest
            -   name: Log into registry
                run: echo "${{ secrets.CONTAINER_REGISTRY_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            -   name: Push image
                run: |
                    docker push ghcr.io/${{ github.repository }}/php:latest
                    docker push ghcr.io/${{ github.repository }}/http:latest

            -   name: Setup SSH Keys and known_hosts
                env:
                    SSH_AUTH_SOCK: /tmp/ssh_agent.sock
                run: |
                    ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                    ssh-add - <<< "${{ secrets.DOCKER_SERVER_SSH_KEY }}"
                    mkdir -p ~/.ssh
                    echo "${{ secrets.DOCKER_SERVER_HOST_FINGERPRINT }}" | base64 -d > ~/.ssh/known_hosts

            -   name: Deployment
                env:
                    SSH_AUTH_SOCK: /tmp/ssh_agent.sock
                run: |
                    docker context create vps --docker host=${{ secrets.DOCKER_SERVER_HOST }}
                    docker context use vps
                    eval ssh-agent
                    docker-compose -f docker-compose.prod.yml pull
                    docker-compose -f docker-compose.prod.yml up -d
